[font]
size = 15
normal = { family = "HackGen35 Console NF", style = "Regular" }
bold   = { family = "HackGen35 Console NF", style = "Bold" }

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
    {key = "Equals",   mods = "Control", action = "None"},
    {key = "-", mods = "Control", action = "None"},
]
